apiVersion: v1
kind: Pod
metadata:
  name: api-pod
  labels:
    app: api-pod
spec:
  containers:
    - name: app
      image: otaviodocker/api-fastfood:1.0
      imagePullPolicy: Always
      ports:
        - name: api-pod
          containerPort: 8080
          protocol: TCP
      env:
        - name: DATABASE_URL
          value: "jdbc:postgresql://postgres-svc:5432/fastfood"
      env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
  restartPolicy: Always