apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  labels:
    name: db-config
data:
  POSTGRES_URL: jdbc:postgresql://postgres-svc:5432/fastfood
  POSTGRES_DB: fastfood
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: 123456