create table tb_category (created_at TIMESTAMP WITHOUT TIME ZONE, deleted_at TIMESTAMP WITHOUT TIME ZONE, id bigserial not null, updated_at TIMESTAMP WITHOUT TIME ZONE, name varchar(255) not null unique, primary key (id));
create table tb_customer (created_at TIMESTAMP WITHOUT TIME ZONE, deleted_at TIMESTAMP WITHOUT TIME ZONE, id bigserial not null, updated_at TIMESTAMP WITHOUT TIME ZONE, cpf varchar(255) not null unique, email varchar(255) not null, name varchar(255) not null, primary key (id));
create table tb_order (created_at TIMESTAMP WITHOUT TIME ZONE, deleted_at TIMESTAMP WITHOUT TIME ZONE, id bigserial not null, updated_at TIMESTAMP WITHOUT TIME ZONE, status varchar(255) check (status in ('DRAFT','SUBMITTED','PREPARING','DELIVERED','CANCELED')), primary key (id));
create table tb_order_item (total_price float(53) not null check (total_price>=0), id bigserial not null, order_id bigint not null, product_id bigint not null, quantity bigint not null check (quantity>=1), primary key (id));
create table tb_product (price float(53) not null, category_id bigint not null, created_at TIMESTAMP WITHOUT TIME ZONE, deleted_at TIMESTAMP WITHOUT TIME ZONE, id bigserial not null, updated_at TIMESTAMP WITHOUT TIME ZONE, description TEXT not null, img_url varchar(255) not null, name varchar(255) not null, primary key (id));
alter table if exists tb_order_item add constraint FKgeobgl2xu916he8vhljktwxnx foreign key (order_id) references tb_order;
alter table if exists tb_order_item add constraint FK4h5xid5qehset7qwe5l9c997x foreign key (product_id) references tb_product;
alter table if exists tb_product add constraint FK8i0sq9mfbpsrabrm2pum9fspo foreign key (category_id) references tb_category;
INSERT INTO tb_category (name, created_at) VALUES ('Snacks', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Drinks', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Desserts', NOW());
INSERT INTO tb_category (name, created_at) VALUES ('Sides', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('X-Burguer', 14.9, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('X-Bacon', 12.9, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('X-Chicken', 14.9, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('X-Fish', 15.9, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('CheeseBurguer', 12.9, 1, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Coca-Cola', 9.9, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Lemonade', 10.9, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Orange Juice', 11.9, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Water', 7.9, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Ice Tea', 10.9, 2, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Vanilla Sundae', 8.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Strawberry Sundae', 8.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Chocolate Sundae', 8.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Vanilla Shake', 13.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Strawberry Shake', 13.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Chocolate Shake', 13.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Vanilla Cone', 5.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Chocolate Cone', 5.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Mixed Cone', 5.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Banana Pie', 7.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Apple Cone', 7.9, 3, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('French Fries', 8.9, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Mustard', 1.9, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Ketchup', 1.9, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Mayonnaise', 1.9, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Barbeque Sauce', 1.9, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_product (name, price, category_id, description, img_url, created_at) VALUES ('Chicken Nuggets', 10.9, 4, 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus vulputate rutrum ullamcorper.', 'https://', NOW());
INSERT INTO tb_customer (name, cpf, email, created_at) VALUES ('John', '20195054016', 'john@email.com', NOW());
INSERT INTO tb_customer (name, cpf, email, created_at) VALUES ('Mary', '81018255095', 'mary@email.com', NOW());
INSERT INTO tb_customer (name, cpf, email, created_at) VALUES ('Jack', '50260304085', 'jack@email.com', NOW());
INSERT INTO tb_customer (name, cpf, email, created_at) VALUES ('Lysa', '38877348070', 'lysa@email.com', NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('DRAFT', 1, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('SUBMITTED', 2, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('DRAFT', 3, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('PREPARING', 4, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('READY', 1, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('SUBMITTED', 3, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('DELIVERED', 2, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('PREPARING', 2, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('READY', 4, NOW());
INSERT INTO tb_order (status, customer_id, created_at) VALUES ('DELIVERED', 4, NOW());
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (2, 1, 1, 14.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (4, 3, 2, 29.8);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (5, 17, 2, 11.8);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (5, 6, 1, 9.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (6, 17, 3, 17.7);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (7, 5, 1, 12.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (7, 2, 1, 12.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (7, 8, 2, 23.8);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (8, 20, 1, 7.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (9, 22, 2, 17.8);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (10, 12, 1, 8.9);
INSERT INTO tb_order_item (order_id, product_id, quantity, total_price) VALUES (10, 15, 1, 13.9);
