apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-pod
spec:
  containers:
    - name: database
      image: postgres
      imagePullPolicy: Always
      ports:
      - containerPort: 5432
        protocol: TCP
      env:
        - name: POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_URL
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: POSTGRES_DB
  restartPolicy: Always
