apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
        - name: app
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres-svc:5432/fastfood"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          image: fiap7soat30/fast-food:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /swagger-ui/index.html
              port: 8080
            initialDelaySeconds: 50
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 2
          resources:
            requests:
              cpu: "20m"
              memory: "500Mi"
            limits:
              cpu: "500m"
              memory: "3Gi"
      restartPolicy: Always