apiVersion: v1
kind: Service
metadata:
  name: api-svc
spec:
  selector:
    app: api-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
  type: NodePort